import random

demographic_pool = [
    {"Age": 19, "Gender": "Male", "Occupation": "University Student (Freshman)", "Marital Status": "Single"},
    {"Age": 22, "Gender": "Female", "Occupation": "Barista (Part-time)", "Marital Status": "Single"},
    {"Age": 24, "Gender": "Male", "Occupation": "Job Seeker / Unemployed", "Marital Status": "Single"},
    {"Age": 25, "Gender": "Female", "Occupation": "Graduate Student", "Marital Status": "Single"},
    {"Age": 26, "Gender": "Male", "Occupation": "Military Officer (Lieutenant)", "Marital Status": "Single"},
    {"Age": 27, "Gender": "Female", "Occupation": "Junior Graphic Designer", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Male", "Occupation": "Software Developer", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Female", "Occupation": "Nurse", "Marital Status": "Single"},
    {"Age": 30, "Gender": "Male", "Occupation": "Fitness Trainer", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Female", "Occupation": "Elementary School Teacher", "Marital Status": "Married"},
    {"Age": 32, "Gender": "Male", "Occupation": "Sales Representative", "Marital Status": "Married"},
    {"Age": 33, "Gender": "Female", "Occupation": "Flight Attendant", "Marital Status": "Single"},
    {"Age": 34, "Gender": "Male", "Occupation": "Chef", "Marital Status": "Married"},
    {"Age": 35, "Gender": "Female", "Occupation": "Freelance Writer", "Marital Status": "Divorced"},
    {"Age": 36, "Gender": "Male", "Occupation": "Construction Worker", "Marital Status": "Married"},
    {"Age": 37, "Gender": "Female", "Occupation": "Stay-at-home Mom", "Marital Status": "Married"},
    {"Age": 38, "Gender": "Male", "Occupation": "Bank Manager", "Marital Status": "Married"},
    {"Age": 39, "Gender": "Female", "Occupation": "Pharmacist", "Marital Status": "Single"},
    {"Age": 40, "Gender": "Male", "Occupation": "Taxi Driver", "Marital Status": "Divorced"},
    {"Age": 41, "Gender": "Female", "Occupation": "Restaurant Owner", "Marital Status": "Married"},
    {"Age": 42, "Gender": "Male", "Occupation": "Police Officer", "Marital Status": "Married"},
    {"Age": 43, "Gender": "Female", "Occupation": "Insurance Agent", "Marital Status": "Divorced"},
    {"Age": 44, "Gender": "Male", "Occupation": "Architect", "Marital Status": "Single"},
    {"Age": 45, "Gender": "Female", "Occupation": "High School Principal", "Marital Status": "Married"},
    {"Age": 46, "Gender": "Male", "Occupation": "Truck Driver", "Marital Status": "Married"},
    {"Age": 47, "Gender": "Female", "Occupation": "Social Worker", "Marital Status": "Single"},
    {"Age": 48, "Gender": "Male", "Occupation": "Factory Supervisor", "Marital Status": "Married"},
    {"Age": 49, "Gender": "Female", "Occupation": "Real Estate Agent", "Marital Status": "Divorced"},
    {"Age": 50, "Gender": "Male", "Occupation": "CEO of Small Business", "Marital Status": "Married"},
    {"Age": 52, "Gender": "Female", "Occupation": "Librarian", "Marital Status": "Single"},
    {"Age": 53, "Gender": "Male", "Occupation": "Bus Driver", "Marital Status": "Married"},
    {"Age": 55, "Gender": "Female", "Occupation": "Housekeeper", "Marital Status": "Widowed"},
    {"Age": 56, "Gender": "Male", "Occupation": "Lawyer", "Marital Status": "Divorced"},
    {"Age": 58, "Gender": "Female", "Occupation": "Accountant", "Marital Status": "Married"},
    {"Age": 59, "Gender": "Male", "Occupation": "Farmer", "Marital Status": "Married"},
    {"Age": 26, "Gender": "Female", "Occupation": "Emergency Room Nurse", "Marital Status": "Single"},
    {"Age": 27, "Gender": "Male", "Occupation": "Software Engineer (Startup)", "Marital Status": "Single"},
    {"Age": 27, "Gender": "Female", "Occupation": "Architectural Designer", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Male", "Occupation": "Medical Resident (Surgery)", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Female", "Occupation": "Public Defender (Lawyer)", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Male", "Occupation": "Fund Manager", "Marital Status": "Married"},
    {"Age": 29, "Gender": "Female", "Occupation": "Flight Attendant", "Marital Status": "Single"},
    {"Age": 30, "Gender": "Male", "Occupation": "Police Detective", "Marital Status": "Married"},
    {"Age": 30, "Gender": "Female", "Occupation": "Journalist", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Male", "Occupation": "Air Traffic Controller", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Female", "Occupation": "Wedding Planner", "Marital Status": "Married"},
    {"Age": 32, "Gender": "Male", "Occupation": "Chef de Cuisine", "Marital Status": "Divorced"},
    {"Age": 34, "Gender": "Female", "Occupation": "University Professor", "Marital Status": "Married"},
    {"Age": 18, "Gender": "Male", "Occupation": "High School Senior", "Marital Status": "Single"},
    {"Age": 23, "Gender": "Female", "Occupation": "Art Student", "Marital Status": "Single"},
    {"Age": 19, "Gender": "Male", "Occupation": "University Freshman", "Marital Status": "Single"},
    {"Age": 21, "Gender": "Female", "Occupation": "Cafe Part-timer", "Marital Status": "Single"},
    {"Age": 23, "Gender": "Male", "Occupation": "Job Seeker", "Marital Status": "Single"},
    {"Age": 24, "Gender": "Female", "Occupation": "Graduate Student", "Marital Status": "Single"},
    {"Age": 25, "Gender": "Male", "Occupation": "Delivery Driver", "Marital Status": "Single"},
    {"Age": 26, "Gender": "Female", "Occupation": "Junior Graphic Designer", "Marital Status": "Single"},
    {"Age": 27, "Gender": "Male", "Occupation": "Sales Associate", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Female", "Occupation": "Nurse", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Male", "Occupation": "Software Developer", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Female", "Occupation": "Flight Attendant", "Marital Status": "Married"},
    {"Age": 30, "Gender": "Male", "Occupation": "Fitness Trainer", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Female", "Occupation": "Elementary School Teacher", "Marital Status": "Married"},
    {"Age": 32, "Gender": "Male", "Occupation": "Police Officer", "Marital Status": "Married"},
    {"Age": 33, "Gender": "Female", "Occupation": "Freelance Writer", "Marital Status": "Single"},
    {"Age": 34, "Gender": "Male", "Occupation": "Chef", "Marital Status": "Married"},
    {"Age": 35, "Gender": "Female", "Occupation": "Bank Teller", "Marital Status": "Divorced"},
    {"Age": 36, "Gender": "Male", "Occupation": "Auto Mechanic", "Marital Status": "Married"},
    {"Age": 37, "Gender": "Female", "Occupation": "Pharmacist", "Marital Status": "Married"},
    {"Age": 38, "Gender": "Male", "Occupation": "Construction Worker", "Marital Status": "Single"},
    {"Age": 39, "Gender": "Female", "Occupation": "Stay-at-home Mom", "Marital Status": "Married"},
    {"Age": 40, "Gender": "Male", "Occupation": "Taxi Driver", "Marital Status": "Divorced"},
    {"Age": 41, "Gender": "Female", "Occupation": "Restaurant Owner", "Marital Status": "Married"},
    {"Age": 42, "Gender": "Male", "Occupation": "Architect", "Marital Status": "Married"},
    {"Age": 43, "Gender": "Female", "Occupation": "Insurance Agent", "Marital Status": "Divorced"},
    {"Age": 44, "Gender": "Male", "Occupation": "High School Teacher", "Marital Status": "Married"},
    {"Age": 45, "Gender": "Female", "Occupation": "Social Worker", "Marital Status": "Single"},
    {"Age": 46, "Gender": "Male", "Occupation": "Truck Driver", "Marital Status": "Married"},
    {"Age": 47, "Gender": "Female", "Occupation": "Real Estate Agent", "Marital Status": "Divorced"},
    {"Age": 48, "Gender": "Male", "Occupation": "Factory Supervisor", "Marital Status": "Married"},
    {"Age": 49, "Gender": "Female", "Occupation": "Librarian", "Marital Status": "Single"},
    {"Age": 50, "Gender": "Male", "Occupation": "Small Business CEO", "Marital Status": "Married"},
    {"Age": 52, "Gender": "Female", "Occupation": "Head Nurse", "Marital Status": "Married"},
    {"Age": 53, "Gender": "Male", "Occupation": "Bus Driver", "Marital Status": "Married"},
    {"Age": 55, "Gender": "Female", "Occupation": "Housekeeper", "Marital Status": "Widowed"},
    {"Age": 56, "Gender": "Male", "Occupation": "Lawyer", "Marital Status": "Divorced"},
    {"Age": 58, "Gender": "Female", "Occupation": "Accountant", "Marital Status": "Married"},
    {"Age": 59, "Gender": "Male", "Occupation": "Farmer", "Marital Status": "Married"},
    {"Age": 60, "Gender": "Female", "Occupation": "Retired Teacher", "Marital Status": "Married"},
    {"Age": 62, "Gender": "Male", "Occupation": "Security Guard", "Marital Status": "Married"},
    {"Age": 63, "Gender": "Female", "Occupation": "Bakery Owner", "Marital Status": "Widowed"},
    {"Age": 65, "Gender": "Male", "Occupation": "Building Janitor", "Marital Status": "Married"},
    {"Age": 67, "Gender": "Female", "Occupation": "Volunteer Worker", "Marital Status": "Widowed"},
    {"Age": 68, "Gender": "Male", "Occupation": "Retired Civil Servant", "Marital Status": "Married"},
    {"Age": 70, "Gender": "Female", "Occupation": "Retired Nurse", "Marital Status": "Widowed"},
    {"Age": 72, "Gender": "Male", "Occupation": "Retired", "Marital Status": "Widowed"},
    {"Age": 74, "Gender": "Female", "Occupation": "Retired", "Marital Status": "Widowed"},
    {"Age": 75, "Gender": "Male", "Occupation": "Author", "Marital Status": "Married"},
    {"Age": 78, "Gender": "Female", "Occupation": "Retired", "Marital Status": "Widowed"},
    {"Age": 80, "Gender": "Male", "Occupation": "Retired", "Marital Status": "Widowed"},
    {"Age": 82, "Gender": "Female", "Occupation": "Nursing Home Resident", "Marital Status": "Widowed"},
    {"Age": 19, "Gender": "Female", "Occupation": "Culinary Student", "Marital Status": "Single"},
    {"Age": 20, "Gender": "Male", "Occupation": "Gas Station Attendant", "Marital Status": "Single"},
    {"Age": 22, "Gender": "Female", "Occupation": "Nail Technician", "Marital Status": "Single"},
    {"Age": 23, "Gender": "Male", "Occupation": "Apprentice Electrician", "Marital Status": "Single"},
    {"Age": 24, "Gender": "Female", "Occupation": "Social Media Manager", "Marital Status": "Single"},
    {"Age": 25, "Gender": "Male", "Occupation": "Paramedic", "Marital Status": "Single"},
    {"Age": 26, "Gender": "Female", "Occupation": "Dental Hygienist", "Marital Status": "Married"},
    {"Age": 27, "Gender": "Male", "Occupation": "Landscape Gardener", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Female", "Occupation": "PhD Researcher", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Male", "Occupation": "Sound Engineer", "Marital Status": "Single"},
    {"Age": 30, "Gender": "Female", "Occupation": "Yoga Instructor", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Male", "Occupation": "Firefighter", "Marital Status": "Married"},
    {"Age": 32, "Gender": "Female", "Occupation": "Wedding Planner", "Marital Status": "Married"},
    {"Age": 33, "Gender": "Male", "Occupation": "Logistics Coordinator", "Marital Status": "Single"},
    {"Age": 34, "Gender": "Female", "Occupation": "Veterinary Technician", "Marital Status": "Divorced"},
    {"Age": 35, "Gender": "Male", "Occupation": "Plumber", "Marital Status": "Married"},
    {"Age": 36, "Gender": "Female", "Occupation": "Florist", "Marital Status": "Married"},
    {"Age": 37, "Gender": "Male", "Occupation": "Subway Driver", "Marital Status": "Single"},
    {"Age": 38, "Gender": "Female", "Occupation": "Piano Teacher", "Marital Status": "Married"},
    {"Age": 39, "Gender": "Male", "Occupation": "Car Dealer", "Marital Status": "Divorced"},
    {"Age": 40, "Gender": "Female", "Occupation": "Hotel Manager", "Marital Status": "Single"},
    {"Age": 41, "Gender": "Male", "Occupation": "Welder", "Marital Status": "Married"},
    {"Age": 42, "Gender": "Female", "Occupation": "Journalist", "Marital Status": "Married"},
    {"Age": 43, "Gender": "Male", "Occupation": "IT Consultant", "Marital Status": "Divorced"},
    {"Age": 44, "Gender": "Female", "Occupation": "Museum Curator", "Marital Status": "Single"},
    {"Age": 45, "Gender": "Male", "Occupation": "Pastor", "Marital Status": "Married"},
    {"Age": 46, "Gender": "Female", "Occupation": "Interior Designer", "Marital Status": "Married"},
    {"Age": 47, "Gender": "Male", "Occupation": "Butcher", "Marital Status": "Widowed"},
    {"Age": 48, "Gender": "Female", "Occupation": "Travel Agent", "Marital Status": "Divorced"},
    {"Age": 49, "Gender": "Male", "Occupation": "University Professor", "Marital Status": "Married"},
    {"Age": 50, "Gender": "Female", "Occupation": "Human Resources Director", "Marital Status": "Married"},
    {"Age": 51, "Gender": "Male", "Occupation": "Postman", "Marital Status": "Married"},
    {"Age": 53, "Gender": "Female", "Occupation": "Jewelry Designer", "Marital Status": "Divorced"},
    {"Age": 54, "Gender": "Male", "Occupation": "Warehouse Manager", "Marital Status": "Married"},
    {"Age": 55, "Gender": "Female", "Occupation": "Real Estate Broker", "Marital Status": "Widowed"},
    {"Age": 57, "Gender": "Male", "Occupation": "Civil Engineer", "Marital Status": "Married"},
    {"Age": 59, "Gender": "Female", "Occupation": "Head Librarian", "Marital Status": "Single"},
    {"Age": 60, "Gender": "Male", "Occupation": "Ship Captain", "Marital Status": "Married"},
    {"Age": 37, "Gender": "Female", "Occupation": "Real Estate Agent", "Marital Status": "Married"},
    {"Age": 38, "Gender": "Male", "Occupation": "High School Teacher", "Marital Status": "Single"},
    {"Age": 39, "Gender": "Female", "Occupation": "Bank Teller", "Marital Status": "Married"},
    {"Age": 40, "Gender": "Male", "Occupation": "Taxi Driver", "Marital Status": "Divorced"},
    {"Age": 41, "Gender": "Female", "Occupation": "Hairdresser / Salon Owner", "Marital Status": "Single"},
    {"Age": 42, "Gender": "Male", "Occupation": "Factory Supervisor", "Marital Status": "Married"},
    {"Age": 43, "Gender": "Female", "Occupation": "Piano Teacher", "Marital Status": "Single"},
    {"Age": 44, "Gender": "Male", "Occupation": "Construction Site Foreman", "Marital Status": "Married"},
    {"Age": 45, "Gender": "Female", "Occupation": "HR Manager", "Marital Status": "Married"},
    {"Age": 46, "Gender": "Male", "Occupation": "Logistics Truck Driver", "Marital Status": "Divorced"},
    {"Age": 47, "Gender": "Female", "Occupation": "Department Store Sales Manager", "Marital Status": "Single"},
    {"Age": 48, "Gender": "Male", "Occupation": "Civil Servant (City Hall)", "Marital Status": "Married"},
    {"Age": 22, "Gender": "Male", "Occupation": "Freelance Video Editor", "Marital Status": "Single"},
    {"Age": 23, "Gender": "Female", "Occupation": "Cosmetics Store Manager", "Marital Status": "Single"},
    {"Age": 24, "Gender": "Male", "Occupation": "Webtoon Artist Assistant", "Marital Status": "Single"},
    {"Age": 25, "Gender": "Female", "Occupation": "Public Relations Intern", "Marital Status": "Single"},
    {"Age": 25, "Gender": "Male", "Occupation": "Gym Instructor", "Marital Status": "Single"},
    {"Age": 26, "Gender": "Female", "Occupation": "Kindergarten Teacher", "Marital Status": "Single"},
    {"Age": 26, "Gender": "Male", "Occupation": "Smartphone App Developer", "Marital Status": "Single"},
    {"Age": 27, "Gender": "Female", "Occupation": "Fashion Stylist Assistant", "Marital Status": "Single"},
    {"Age": 27, "Gender": "Male", "Occupation": "Hotel Front Desk Agent", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Female", "Occupation": "UI/UX Designer", "Marital Status": "Married"},
    {"Age": 28, "Gender": "Male", "Occupation": "Police Patrol Officer", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Female", "Occupation": "Content Marketer", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Male", "Occupation": "Investment Banking Analyst", "Marital Status": "Single"},
    {"Age": 30, "Gender": "Female", "Occupation": "Wedding Photographer", "Marital Status": "Married"},
    {"Age": 30, "Gender": "Male", "Occupation": "Automotive Engineer", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Female", "Occupation": "Hospital Administrator", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Male", "Occupation": "Sous Chef", "Marital Status": "Married"},
    {"Age": 32, "Gender": "Female", "Occupation": "Pharmaceutical Sales Rep", "Marital Status": "Married"},
    {"Age": 32, "Gender": "Male", "Occupation": "High School Math Teacher", "Marital Status": "Single"},
    {"Age": 33, "Gender": "Female", "Occupation": "Broadcast Writer", "Marital Status": "Single"},
    {"Age": 33, "Gender": "Male", "Occupation": "Logistics Manager", "Marital Status": "Married"},
    {"Age": 34, "Gender": "Female", "Occupation": "Pilates Instructor", "Marital Status": "Divorced"},
    {"Age": 34, "Gender": "Male", "Occupation": "Fund Manager", "Marital Status": "Married"},
    {"Age": 35, "Gender": "Female", "Occupation": "Corporate Lawyer", "Marital Status": "Married"},
    {"Age": 36, "Gender": "Male", "Occupation": "Solar Panel Technician", "Marital Status": "Married"},
    {"Age": 37, "Gender": "Female", "Occupation": "Restaurant Franchise Owner", "Marital Status": "Married"},
    {"Age": 38, "Gender": "Male", "Occupation": "IT Project Manager", "Marital Status": "Single"},
    {"Age": 39, "Gender": "Female", "Occupation": "Dermatologist", "Marital Status": "Married"},
    {"Age": 39, "Gender": "Male", "Occupation": "Film Director", "Marital Status": "Divorced"},
    {"Age": 40, "Gender": "Female", "Occupation": "HR Department Head", "Marital Status": "Married"},
    {"Age": 41, "Gender": "Male", "Occupation": "Bus Driver", "Marital Status": "Married"},
    {"Age": 42, "Gender": "Female", "Occupation": "Gallery Curator", "Marital Status": "Single"},
    {"Age": 42, "Gender": "Male", "Occupation": "Mechanical Engineer", "Marital Status": "Married"},
    {"Age": 43, "Gender": "Female", "Occupation": "Private Tutor", "Marital Status": "Divorced"},
    {"Age": 44, "Gender": "Male", "Occupation": "Construction Site Foreman", "Marital Status": "Married"},
    {"Age": 45, "Gender": "Female", "Occupation": "Bank Branch Manager", "Marital Status": "Married"},
    {"Age": 46, "Gender": "Male", "Occupation": "Taxi Driver", "Marital Status": "Divorced"},
    {"Age": 47, "Gender": "Female", "Occupation": "Insurance Claims Adjuster", "Marital Status": "Married"},
    {"Age": 48, "Gender": "Male", "Occupation": "University Professor (Engineering)", "Marital Status": "Married"},
    {"Age": 49, "Gender": "Female", "Occupation": "Interior Design Firm CEO", "Marital Status": "Single"},
    {"Age": 50, "Gender": "Male", "Occupation": "Airline Pilot", "Marital Status": "Married"},
    {"Age": 51, "Gender": "Female", "Occupation": "Head Nurse", "Marital Status": "Divorced"},
    {"Age": 52, "Gender": "Male", "Occupation": "Real Estate Developer", "Marital Status": "Married"},
    {"Age": 53, "Gender": "Female", "Occupation": "Social Worker", "Marital Status": "Widowed"},
    {"Age": 54, "Gender": "Male", "Occupation": "Factory Quality Control Manager", "Marital Status": "Married"},
    {"Age": 55, "Gender": "Female", "Occupation": "Jewelry Shop Owner", "Marital Status": "Married"},
    {"Age": 56, "Gender": "Male", "Occupation": "Truck Driver", "Marital Status": "Divorced"},
    {"Age": 57, "Gender": "Female", "Occupation": "School Principal", "Marital Status": "Married"},
    {"Age": 58, "Gender": "Male", "Occupation": "Building Maintenance Supervisor", "Marital Status": "Married"},
    {"Age": 59, "Gender": "Female", "Occupation": "Government Official", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Female", "Occupation": "ER Nurse (Emergency Room)", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Male", "Occupation": "Medical Resident (Intern)", "Marital Status": "Single"},
    {"Age": 32, "Gender": "Female", "Occupation": "911 Dispatcher", "Marital Status": "Single"},
    {"Age": 34, "Gender": "Male", "Occupation": "Firefighter (Rescue Team)", "Marital Status": "Married"},
    {"Age": 35, "Gender": "Female", "Occupation": "Hospice Caregiver", "Marital Status": "Divorced"},
    {"Age": 38, "Gender": "Male", "Occupation": "Crime Scene Cleaner", "Marital Status": "Single"},
    {"Age": 40, "Gender": "Female", "Occupation": "Social Worker (Child Protection)", "Marital Status": "Married"},
    {"Age": 42, "Gender": "Male", "Occupation": "Veterinarian", "Marital Status": "Single"},
    {"Age": 45, "Gender": "Female", "Occupation": "Psychiatric Ward Nurse", "Marital Status": "Divorced"},
    {"Age": 62, "Gender": "Male", "Occupation": "Security Guard", "Marital Status": "Married"},
    {"Age": 63, "Gender": "Female", "Occupation": "Bakery Owner", "Marital Status": "Widowed"},
    {"Age": 65, "Gender": "Male", "Occupation": "Building Janitor", "Marital Status": "Married"},
    {"Age": 67, "Gender": "Female", "Occupation": "Volunteer Worker", "Marital Status": "Widowed"},
    {"Age": 68, "Gender": "Male", "Occupation": "Retired Civil Servant", "Marital Status": "Married"},
    {"Age": 70, "Gender": "Female", "Occupation": "Retired Nurse", "Marital Status": "Widowed"},
    {"Age": 72, "Gender": "Male", "Occupation": "Retired", "Marital Status": "Widowed"},
    {"Age": 74, "Gender": "Female", "Occupation": "Retired", "Marital Status": "Widowed"},
    {"Age": 75, "Gender": "Male", "Occupation": "Author", "Marital Status": "Married"},
    {"Age": 78, "Gender": "Female", "Occupation": "Retired", "Marital Status": "Widowed"},
    {"Age": 80, "Gender": "Male", "Occupation": "Retired", "Marital Status": "Widowed"},
    {"Age": 82, "Gender": "Female", "Occupation": "Nursing Home Resident", "Marital Status": "Widowed"},
    {"Age": 25, "Gender": "Male", "Occupation": "Convenience Store Night Clerk", "Marital Status": "Single"},
    {"Age": 36, "Gender": "Male", "Occupation": "Deep Sea Fisherman", "Marital Status": "Married"},
    {"Age": 37, "Gender": "Female", "Occupation": "Factory Line Worker (Night Shift)", "Marital Status": "Single"},
    {"Age": 43, "Gender": "Male", "Occupation": "Long-haul Truck Driver", "Marital Status": "Divorced"},
    {"Age": 44, "Gender": "Female", "Occupation": "Subway Cleaner (Night Shift)", "Marital Status": "Widowed"},
    {"Age": 46, "Gender": "Male", "Occupation": "Lighthouse Keeper / Remote Station", "Marital Status": "Single"},
    {"Age": 48, "Gender": "Male", "Occupation": "Subway Driver (Underground)", "Marital Status": "Married"},
    {"Age": 52, "Gender": "Female", "Occupation": "Toll Booth Collector", "Marital Status": "Divorced"},
    {"Age": 58, "Gender": "Male", "Occupation": "Night Watchman", "Marital Status": "Widowed"},
    {"Age": 60, "Gender": "Female", "Occupation": "Kitchen Porter (Dishwasher)", "Marital Status": "Widowed"},
    {"Age": 20, "Gender": "Female", "Occupation": "K-Pop Trainee", "Marital Status": "Single"},
    {"Age": 22, "Gender": "Male", "Occupation": "Professional Gamer", "Marital Status": "Single"},
    {"Age": 27, "Gender": "Female", "Occupation": "Webtoon Artist (Weekly Deadlines)", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Male", "Occupation": "Struggling Actor", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Female", "Occupation": "Civil Service Exam Student (4th year)", "Marital Status": "Single"},
    {"Age": 30, "Gender": "Male", "Occupation": "Startup Founder (Facing Bankruptcy)", "Marital Status": "Single"},
    {"Age": 32, "Gender": "Female", "Occupation": "Interpreter (Simultaneous)", "Marital Status": "Single"},
    {"Age": 34, "Gender": "Male", "Occupation": "Air Traffic Controller", "Marital Status": "Married"},
    {"Age": 35, "Gender": "Female", "Occupation": "PhD Candidate (Thesis Pressure)", "Marital Status": "Single"},
    {"Age": 36, "Gender": "Male", "Occupation": "Day Laborer (Construction)", "Marital Status": "Single"},
    {"Age": 21, "Gender": "Female", "Occupation": "Content Moderator (Filtering Violence)", "Marital Status": "Single"},
    {"Age": 23, "Gender": "Male", "Occupation": "Gig Economy Courier (Rider)", "Marital Status": "Single"},
    {"Age": 26, "Gender": "Female", "Occupation": "Influencer (Target of Cyberbullying)", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Male", "Occupation": "Cryptocurrency Trader", "Marital Status": "Single"},
    {"Age": 33, "Gender": "Female", "Occupation": "Data Entry Clerk", "Marital Status": "Married"},
    {"Age": 38, "Gender": "Male", "Occupation": "Audit Team Manager", "Marital Status": "Married"},
    {"Age": 40, "Gender": "Female", "Occupation": "News Anchor", "Marital Status": "Single"},
    {"Age": 45, "Gender": "Male", "Occupation": "M&A Consultant", "Marital Status": "Divorced"},
    {"Age": 47, "Gender": "Female", "Occupation": "Bankruptcy Lawyer", "Marital Status": "Single"},
    {"Age": 53, "Gender": "Male", "Occupation": "Unemployed (Laid off recently)", "Marital Status": "Married"},
    {"Age": 23, "Gender": "Female", "Occupation": "Professional Ballet Dancer", "Marital Status": "Single"},
    {"Age": 25, "Gender": "Male", "Occupation": "Orchestra Musician (Violinist)", "Marital Status": "Single"},
    {"Age": 27, "Gender": "Female", "Occupation": "Voice Actress (Freelance)", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Male", "Occupation": "Stage Lighting Technician", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Female", "Occupation": "Art Restorer", "Marital Status": "Married"},
    {"Age": 33, "Gender": "Male", "Occupation": "Film Editor (Post-production)", "Marital Status": "Single"},
    {"Age": 35, "Gender": "Female", "Occupation": "Ghostwriter", "Marital Status": "Divorced"},
    {"Age": 38, "Gender": "Male", "Occupation": "Tattoo Artist", "Marital Status": "Single"},
    {"Age": 40, "Gender": "Female", "Occupation": "Musical Theater Actress", "Marital Status": "Married"},
    {"Age": 45, "Gender": "Male", "Occupation": "Documentary Director", "Marital Status": "Divorced"},
    {"Age": 24, "Gender": "Male", "Occupation": "White Hat Hacker (Security Analyst)", "Marital Status": "Single"},
    {"Age": 26, "Gender": "Female", "Occupation": "Game QA Tester", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Male", "Occupation": "Data Center Technician (Night Shift)", "Marital Status": "Single"},
    {"Age": 30, "Gender": "Female", "Occupation": "UX/UI Researcher", "Marital Status": "Married"},
    {"Age": 32, "Gender": "Male", "Occupation": "Cloud Architect", "Marital Status": "Single"},
    {"Age": 34, "Gender": "Female", "Occupation": "Bioinformatics Scientist", "Marital Status": "Married"},
    {"Age": 39, "Gender": "Male", "Occupation": "Robotics Engineer", "Marital Status": "Married"},
    {"Age": 42, "Gender": "Female", "Occupation": "Technical Support Lead", "Marital Status": "Divorced"},
    {"Age": 47, "Gender": "Male", "Occupation": "Legacy System Maintainer (COBOL)", "Marital Status": "Widowed"},
    {"Age": 50, "Gender": "Female", "Occupation": "IT Auditor", "Marital Status": "Single"},
    {"Age": 22, "Gender": "Female", "Occupation": "Pet Groomer", "Marital Status": "Single"},
    {"Age": 29, "Gender": "Male", "Occupation": "Sommelier", "Marital Status": "Single"},
    {"Age": 31, "Gender": "Female", "Occupation": "Wedding Dress Designer", "Marital Status": "Single"},
    {"Age": 33, "Gender": "Male", "Occupation": "Private Investigator", "Marital Status": "Divorced"},
    {"Age": 36, "Gender": "Female", "Occupation": "Interpreter for the Deaf (Sign Language)", "Marital Status": "Married"},
    {"Age": 37, "Gender": "Male", "Occupation": "Zookeeper", "Marital Status": "Married"},
    {"Age": 41, "Gender": "Female", "Occupation": "Gemologist (Jewelry Appraiser)", "Marital Status": "Single"},
    {"Age": 43, "Gender": "Male", "Occupation": "Bodyguard", "Marital Status": "Single"},
    {"Age": 46, "Gender": "Female", "Occupation": "Matchmaker / Couple Manager", "Marital Status": "Married"},
    {"Age": 49, "Gender": "Male", "Occupation": "Auctioneer", "Marital Status": "Married"},
    {"Age": 25, "Gender": "Male", "Occupation": "Elevator Repair Technician", "Marital Status": "Single"},
    {"Age": 28, "Gender": "Female", "Occupation": "Forensic Science Technician", "Marital Status": "Single"},
    {"Age": 30, "Gender": "Male", "Occupation": "Oil Rig Worker", "Marital Status": "Single"},
    {"Age": 34, "Gender": "Female", "Occupation": "Landscape Architect", "Marital Status": "Married"},
    {"Age": 38, "Gender": "Male", "Occupation": "Crane Operator", "Marital Status": "Married"},
    {"Age": 42, "Gender": "Female", "Occupation": "Custom Furniture Maker", "Marital Status": "Divorced"},
    {"Age": 44, "Gender": "Male", "Occupation": "Shipbuilder", "Marital Status": "Married"},
    {"Age": 48, "Gender": "Male", "Occupation": "Waste Management Officer", "Marital Status": "Married"},
    {"Age": 52, "Gender": "Female", "Occupation": "Tailor / Seamstress", "Marital Status": "Widowed"},
    {"Age": 55, "Gender": "Male", "Occupation": "Pest Control Specialist", "Marital Status": "Divorced"},
    {"Age": 26, "Gender": "Female", "Occupation": "Special Education Teacher", "Marital Status": "Single"},
    {"Age": 32, "Gender": "Male", "Occupation": "Archivist", "Marital Status": "Single"},
    {"Age": 35, "Gender": "Female", "Occupation": "Speech Therapist", "Marital Status": "Married"},
    {"Age": 37, "Gender": "Male", "Occupation": "University Admissions Officer", "Marital Status": "Married"},
    {"Age": 40, "Gender": "Female", "Occupation": "Nutritionist / Dietitian", "Marital Status": "Divorced"},
    {"Age": 45, "Gender": "Male", "Occupation": "Meteorologist", "Marital Status": "Married"},
    {"Age": 53, "Gender": "Female", "Occupation": "Museum Docent", "Marital Status": "Married"},
    {"Age": 58, "Gender": "Male", "Occupation": "School Bus Driver", "Marital Status": "Widowed"},
    {"Age": 62, "Gender": "Female", "Occupation": "Part-time Census Taker", "Marital Status": "Married"},
    {"Age": 65, "Gender": "Male", "Occupation": "Forest Ranger", "Marital Status": "Widowed"}
]



def get_demographics(args):
    return random.choice(demographic_pool)



if __name__ == "__main__":
    args = None
    demographics = get_demographics(args)
    import IPython; IPython.embed(); exit(1)

